name: Rust

on: [push, pull_request]

jobs:
  check_n_test:
    name: cargo check & test
    uses: noir-lang/.github/.github/workflows/rust-test.yml@phated/only-lock-when-exists

  clippy:
    name: cargo clippy
    uses: noir-lang/.github/.github/workflows/rust-clippy.yml@phated/only-lock-when-exists

  format:
    name: cargo fmt
    uses: noir-lang/.github/.github/workflows/rust-format.yml@phated/only-lock-when-exists

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            **/*.{md,rs}
          incremental_files_only: true # Run this action on files which have changed in PR
          strict: false # Do not fail, if a spelling mistake is found (This can be annoying for contributors)
